name: Release Tag

on:
  pull_request:
    branches:
      - 'release-*'

jobs:
  deployment:
    name: Setup, Build, and Deploy
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Current Date and Time
        id: current_time
        run: |
          echo "TAG_TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          echo github.event.pull_request.merged

      - name: Bump version and push tag
        id: tag_version
        run: |
          git tag ${{ env.TAG_TIMESTAMP }}
          git push origin ${{ env.TAG_TIMESTAMP }}

      - name: Generate Change Log
        id: drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG_TIMESTAMP }}
          name: Release ${{ env.TAG_TIMESTAMP }}
          body: ${{ steps.drafter.outputs.changelog }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DEV_DOCKER_ID }}
          password: ${{ secrets.DEV_DOCKER_PW }}

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nowgnas/CAC-discovery:${{ env.TAG_TIMESTAMP }}, nowgnas/CAC-discovery:latest
